server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wallet?characterEncoding=UTF-8&serverTimezone=GMT&useSSL=false
    username: root
    password:
  jpa:
    show-sql: true
    database: mysql
